name: Java Maven CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  verify-project:
    runs-on: ubuntu-latest

    steps:

      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Configure Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Execute Unit Tests
        run: mvn clean test